MODEL:
  META_ARCHITECTURE: "DepthRCNN"
  BACKBONE:
    CONV_BODY: "MY_NET"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    MLP_HEAD_DIM: 2048
    NUM_CLASSES: 7
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
  MASK_ON: True
  RESNETS:
    BACKBONE_OUT_CHANNELS: 2048
#  RETINANET:
#    NUM_CLASSES: 7

DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_test",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 2500
TEST:
  IMS_PER_BATCH: 1

INPUT:
  MIN_SIZE_TRAIN: (600,)
# Maximum size of the side of the image during training
  MAX_SIZE_TRAIN: 800
# Size of the smallest side of the image during testing
  MIN_SIZE_TEST: 600
# Maximum size of the side of the image during testing
  MAX_SIZE_TEST: 800

OUTPUT_DIR: "./output/my_MYDEPTHCOCO_my_net"
