MODEL:
  META_ARCHITECTURE: "DepthRCNN"
  BACKBONE:
    CONV_BODY: "RedNet-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
#  ROI_BOX_HEAD:
#    NUM_CLASSES: 7
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
  MASK_ON: True
#  RETINANET:
#    NUM_CLASSES: 7
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_test",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 200
TEST:
  IMS_PER_BATCH: 1


